import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';

export type RefreshTokenDocument = HydratedDocument<RefreshToken>;

@Schema({ collection: 'refresh_tokens', timestamps: true })
export class RefreshToken {
  /**
   * Token ID (UUID, auto-generated by the service)
   */
  @Prop({ type: String })
  _id: string;

  /**
   * User ID who owns this token
   */
  @Prop({ type: String, required: true })
  userId: string;

  /**
   * Hash of the refresh token (never stored plaintext)
   * This allows us to recognize tokens without revealing them in the database
   */
  @Prop({ type: String, required: true })
  tokenHash: string;

  /**
   * Expiration time for this token
   */
  @Prop({ type: Date, required: true })
  expiresAt: Date;

  /**
   * If this token was rotated, the ID of the new token that replaced it
   * This is used for reuse detection: if a client presents a token that has
   * a replacedByToken set, and we can verify the signature still matches,
   * we know the token was already rotated and we need to detect the reuse.
   */
  @Prop({ type: String })
  replacedByTokenId?: string;

  /**
   * Created at timestamp (auto-managed by Mongoose timestamps)
   */
  @Prop()
  createdAt: Date;

  /**
   * Updated at timestamp (auto-managed by Mongoose timestamps)
   */
  @Prop()
  updatedAt: Date;
}

export const RefreshTokenSchema = SchemaFactory.createForClass(RefreshToken);

// Index for fast lookups by userId and expiry
RefreshTokenSchema.index({ userId: 1, expiresAt: 1 });

// Index for cleaning up expired tokens
RefreshTokenSchema.index({ expiresAt: 1 }, { expireAfterSeconds: 0 });
